source "http://rubygems.org"

gem 'veewee', :git => 'git://github.com/jedi4ever/veewee.git'
gem 'vagrant', '1.0.3'
gem 'puppet_acceptance', :git => 'git://github.com/puppetlabs/puppet-acceptance.git'
