# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "centos-58-64bit"
  config.vm.box_url = "https://s3.amazonaws.com/kbarber-puppetlabs-firewall/vagrant/centos-58-64bit.box"

  config.vm.provision :shell do |shell|
    shell.inline = <<-EOS
# TODO: install epel
# TODO: install git
    EOS
  end
end
